# Site settings
title: "invisiblethreat"
email: scott@invisiblethreat.ca
description: ""
baseurl: ""
url: "https://invisiblethreat.ca"
title_description: "Information security, code, technology, and other random bits."
title_image: "/images/gravatar.png"
google_analytics: ""
github_repository: https://github.com/invisiblethreat/invisiblethreat.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: blacktip
github_username: invisiblethreat
linkedin_link: https://ca.linkedin.com/in/walshs
mastodon_instance: infosec.exchange
mastodon_username: invisiblethreat

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: ["vendor", "README.md", "LICENSE"]
