# Site settings
title: "invisiblethreat"
email: scott@invisiblethreat.ca
description: "Your hands can't hit what your eyes can't see."
baseurl: ""
url: "https://www.invisiblethreat.ca"
title_description: "Information security, code, technology, and other random bits."
title_image: "/images/gravatar.png"
google_analytics: ""
disqus_account: invisiblethreat
github_repository: https://github.com/invisiblethreat/invisiblethreat.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: blacktip
github_username: invisiblethreat
linkedin_link: https://ca.linkedin.com/in/walshs

# Track hits
ga_tag: UA-33788997-1

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: ["vendor", "README.md", "LICENSE"]

